DRAFT: Adds Sqlserver to benchmark/analysis
rothaarlappen/pandas-udfs-to-sql pull request #1
Opened 2023-01-30 00:02 UTC by rothaarlappen

Adds sql-server tpch-data setup and translated sql scripts

2023-02-04 11:03 UTC, Tratori approved these changes

2023-02-04 11:03 UTC, Tratori commented on src/database/__init__.py
> +    print(connectionstring())
looks like debugging print to me

2023-02-04 11:03 UTC, Tratori commented on src/datasetup/setup_tpch.py
> +    master_name = "master"
why call this `master_name`?

2023-02-05 14:46 UTC, rothaarlappen commented on src/database/__init__.py
> +    print(connectionstring())
you're right..

2023-02-05 14:49 UTC, Tratori requested changes

2023-02-05 14:49 UTC, Tratori commented on src/evaluation/benchmark.py
>                      "original", pipeline_file, benchmark_results_pipeline_persist
I think we should add sql_flavor here as a parameter as well. I don't expect different runtimes, but we should back that up with data...

2023-02-05 15:06 UTC, Tratori approved these changes

2023-02-06 13:23 UTC, merged